#!/usr/bin/env python3

import sys
import re

def main():
    print("Running commit-msg hook...")
    if len(sys.argv) < 2:
        sys.exit(1)

    commit_msg_file = sys.argv[1]


    with open(commit_msg_file, 'r') as file:
        commit_msg = file.read().strip()

    # Debugging print statements
    print("Commit message file:", commit_msg_file)
    print("Commit message:", commit_msg)

    # Define regex pattern for commit message format
    pattern = r"^\[#\d+\] .+"

    # Check if commit message matches the pattern
    if re.match(pattern, commit_msg):
        print("Commit message format is correct.")
    else:
        print("Error: Commit message format is incorrect. It should be in the format '[#1234] commit message after the numbers'.")
        sys.exit(1)
    print("==========End of commit-msg hook==========")
if __name__ == "__main__":
    main()